=== Jameslovecs/groovity/http-auth/http-auth-server/src/main/resources/auth.dtd
<!ELEMENT auth (basic|digest|signature)+>

<!ELEMENT basic (realm,(passwords|passwordChecker)+,(acl|accessController)*) >
<!ELEMENT digest (realm,(passwords|passwordDigester)+,(maxNonceAge|nonceSecret|domain|acl|accessController)*) >
<!ELEMENT signature (realm,(keystore|keys)+,(drift|headers|acl|accessController)*) >

<!ELEMENT realm (#PCDATA) >
<!ELEMENT passwords (keyId,password)+ >

<!ELEMENT keyId (#PCDATA) >
<!ELEMENT password (#PCDATA) >

<!ELEMENT passwordChecker EMPTY >
<!ATTLIST passwordChecker class CDATA #REQUIRED>

<!ELEMENT passwordDigester EMPTY >
<!ATTLIST passwordDigester class CDATA #REQUIRED>

<!ELEMENT accessController EMPTY >
<!ATTLIST accessController class CDATA #REQUIRED>

<!ELEMENT acl (keyId)+ >

<!ELEMENT keystore (location,type,ttl,password) >
<!ELEMENT location (#PCDATA) >
<!ELEMENT type (#PCDATA) >
<!ELEMENT ttl (#PCDATA) >

<!ELEMENT keys (keyId,key)+ >
<!ELEMENT key (#PCDATA) >
<!ATTLIST key algorithm CDATA "hmac-sha256" >

<!ELEMENT drift (#PCDATA) >
<!ELEMENT headers (#PCDATA) >

<!ELEMENT maxNonceAge (#PCDATA) >
<!ELEMENT nonceSecret (#PCDATA) >
<!ELEMENT domain (#PCDATA) >

=== Jameslovecs/groovity/http-auth/http-auth-sample-webapp/src/main/webapp/WEB-INF/auth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auth SYSTEM "auth.dtd">
<auth>
	<!-- <basic>
		<realm>
			Basic Users
		</realm>
		<passwords>
			<keyId>wonton</keyId>
			<password>pickle</password>
		</passwords>
	</basic> -->
	<digest>
		<realm>
			Digest Users
		</realm>
		<passwords>
			<keyId>wicked</keyId>
			<password>sterling</password>
		</passwords>
	</digest>
	<signature>
		<realm>API Users</realm>
		<keys>
			<keyId>apiUser123</keyId>
			<key algorithm="hmac-sha256">someBase64Secret</key>
		</keys>
		<headers>(request-target) host date</headers>
	</signature>
    <!--<signature>
        <realm>RSA User</realm>
        <keystore>
            <location>file:/Users/kobar004/server_keystore.jceks</location>
            <type>JCEKS</type>
            <ttl>1000</ttl>
            <password>publicPassword</password>
        </keystore>
    </signature>-->
</auth>
